name: Validate Kotlin Code

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run ktlint with Gradle
        run: |
          chmod +x gradlew
          ./gradlew check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: adopt
          java-package: jre
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x check

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: adopt
          java-package: jre
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run tests with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test -x check
      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: build/reports/tests/test
      - name: Upload jaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: build/reports/jacoco/test/html
